project:
  type: website
  output-dir: docs

website:
  title: "Ethical Algorithms for the Modern Clinician"
  page-navigation: true
  repo-url: https://github.com/eamc-penn/eamc-penn.github.io
  repo-actions: [issue]
  favicon: /images/favicon.ico
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - text: Modules
        menu:
          - href: ml.qmd
            text: Intro to Machine Learning
          - href: bias.qmd
            text: Bias and Fairness
          - href: privacy.qmd
            text: Privacy and Anonymization
          - href: interpretability.qmd
            text: Algorithmic Interpretability
          - href: genai.qmd
            text: Generative AI
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/eamc-penn/eamc
          - text: Report an Issue
            href: https://forms.gle/4hEf83U935U89HWg9
      
  body-footer: |
    <p style="text-align: center;margin-top: 20px;">Made with &#x2764; by the EAMC Team &copy;2024.</p>

format:
  html:
    theme:
      light: [cerulean, styles/default.scss]
      dark: [cerulean, styles/dark-theme.scss]
    toc: true
    smooth-scroll: true
    anchor-sections: true
    fontsize: 16px
    reference-location: margin
    citation-location: margin
    date: last-modified
  pdf: default
